
<?php
/*
 * Copyright © Improntus All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 *
 * @var \Magento\Checkout\Block\Onepage\Success $block
 * @var \Improntus\ProntoPaga\ViewModel\Onepage\FinalPage $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getViewModel();
$paymentInfo = $viewModel->getPaymentInfo();
?>

<?php if ($paymentInfo && $viewModel->useCustomPages()):  ?>
    <?php $status =  $paymentInfo['status']; ?>
    <div class="pp-payment-details">
        <div class="content <?= $escaper->escapeHtml($status) ?>">
            <b>Detalles del pago con <?= $escaper->escapeHtml($paymentInfo['method']) ?> </b>
            <div>
                • Respuesta de la Transacción: <b><?= $escaper->escapeHtml($status) ?></b>
            </div>
            <div>
                • Método de pago: <b><?= $escaper->escapeHtml($paymentInfo['method']) ?></b>
            </div>
            <div>
                • Monto: <b><?= $escaper->escapeHtml($viewModel->formatPrice($paymentInfo['amount'])) ?></b>
            </div>
            <div>
                • Orden de compra: <b><?= $escaper->escapeHtml($paymentInfo['order']) ?></b>
            </div>
            <div>
                • Tipo de pago: <b><?= $escaper->escapeHtml($paymentInfo['method_type']) ?></b>
            </div>
        </div>
    </div>
<?php endif; ?>
