
<?php
/*
 * Copyright © Improntus All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 *
 * @var \Magento\Checkout\Block\Onepage\Success $block
 * @var \Improntus\ProntoPaga\ViewModel\Onepage\FinalPage $viewModel
 */

$viewModel = $block->getViewModel();
$paymentInfo = $viewModel->getPaymentInfo();
?>

<?php if ($paymentInfo && $viewModel->useCustomPages()):  ?>
    <?php $status =  $paymentInfo['status']; ?>
    <div class="pp-payment-details">
        <div class="content <?= $status?>">
            <b>Detalles del pago con <?= $paymentInfo['method'] ?> </b>
            <div>
                • Respuesta de la Transacción: <b><?= $status ?></b>
            </div>
            <div>
                • Método de pago: <b><?= $paymentInfo['method'] ?></b>
            </div>
            <div>
                • Monto: <b><?= $viewModel->formatPrice($paymentInfo['amount']) ?></b>
            </div>
            <div>
                • Orden de compra: <b><?= $paymentInfo['order'] ?></b>
            </div>
            <div>
                • Tipo de pago: <b><?= $paymentInfo['method_type'] ?></b>
            </div>
        </div>
    </div>
<?php endif; ?>
