<?php
/*
 * Copyright © Improntus All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Improntus\ProntoPaga\ViewModel\Detail $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getViewModel();
$transaction = $viewModel->getTransactionData();
?>

<div class="transaction-content">
    <div class="table-wrapper data-history">
        <table class="data table table-data-items history" id="my-data-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Grid Record')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $escaper->escapeHtml(__('ID')) ?></th>
                        <th scope="col" class="col order_id"><?= $escaper->escapeHtml(__('Order Id')) ?></th>
                        <th scope="col" class="col payment_method"><?= $escaper->escapeHtml(__('Payment Method')) ?></th>
                        <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col createt_at"><?= $escaper->escapeHtml(__('Created At')) ?></th>
                        <th scope="col" class="col transaction_id"><?= $escaper->escapeHtml(__('Transaction Id')) ?></th>
                    </tr>
                </thead>
            <tbody>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('ID')) ?>" class="col id">
                        <?= $escaper->escapeHtml($transaction->getEntityId()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Order Id')) ?>" class="col order_id">
                        <?= $escaper->escapeHtml($transaction->getOrderId()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Payment Method')) ?>" class="col payment_method">
                        <?= $escaper->escapeHtml($transaction->getPaymentMethod()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status">
                        <?= $escaper->escapeHtml($transaction->getStatus()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Created At')) ?>" class="col created_at">
                        <?= $escaper->escapeHtml($viewModel->getFormattedDate($transaction->getCreatedAt())) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Transaction Id')) ?>" class="col transaction_id">
                        <?= $escaper->escapeHtml($transaction->getTransactionId()) ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <h2>Requests</h2>
    <button class="beauty">Prettify JSON</button>
    <button class="beauty" style="display: none;">Unprettify JSON</button>

    <figure class="unformatted-data">
        <blockquote>
            <?= $escaper->escapeHtml($transaction->getRequestBody()) ?>
        </blockquote>
        <blockquote>
            <?= $escaper->escapeHtml($transaction->getRequestResponse()) ?>
        </blockquote>
    </figure>

    <figure class="formatted-data">
        <p class="request-body"></p>
        <p class="request-response"></p>
    </figure>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Improntus_ProntoPaga/js/beautify" : {
                "request-body" : <?= $escaper->escapeHtml($transaction->getRequestBody()) ?>,
                "request-response" : <?= $escaper->escapeHtml($transaction->getRequestResponse()) ?>
            }
        }
    }
</script>
