<?php
/**
 * Copyright © Improntus All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
?>

<div class="improntus-prontopaga modal validate" id="modal">
    <div class="modal-body-content">
        <figure class="formatted-data">
            <blockquote>
            </blockquote>
        </figure>
    </div>
</div>

<script type="text/javascript">
    require([
        "prototype"
    ], function () {
        window.validateUrl = '<?= /** @noEscape */ $block->getUrl('improntus_prontopaga/transaction/validate')?>';
    });
</script>
